#!/bin/bash
# Set GAMEDIR to the current directory and set logfile
GAMEDIR="$PWD"
LOGFILE="$GAMEDIR/patchlog.txt"

# Redirect output and error to the log file
exec > >(tee -a "$LOGFILE") 2>&1
echo "GAMEDIR is set to: $GAMEDIR"

# Exports
export LD_LIBRARY_PATH="/usr/lib:$GAMEDIR/lib:$GAMEDIR/tools/libs:$LD_LIBRARY_PATH"
export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"
export TOOLDIR="$GAMEDIR/tools"
export TMPDIR="$GAMEDIR/tmp"
export PATH="$GAMEDIR/tools:$PATH"

# Permissions
chmod 666 /dev/uinput
chmod 777 "$TOOLDIR/gmKtool.py"
chmod 777 "$TOOLDIR/oggenc"

cd "$GAMEDIR"

apply_xdelta() {
    # Check if the data.win file exists and apply xdelta
    if [ -f "data.win" ]; then
        echo "Applying xdelta patch"
        output=$(xdelta3 -d -s "data.win" -f "./tools/patches/neon.xdelta" "game.droid" 2>&1)
        if [ $? -eq 0 ]; then
            echo "Patch applied successfully"
            echo "$output"
            rm "data.win"
        else
            echo "Failed to apply patch"
            echo "$output"
            exit 1
        fi
    fi
}

compress_audio() {
    # Compress audio
    echo "Compressing audio..."
    sleep 3
    mkdir -p "$TMPDIR"

    # Run the compression tool
    PYTHON=$(which python3)
    $PYTHON ./tools/gmKtool.py -vvv -m 1000 -r -b 64 -d "$TMPDIR" "$GAMEDIR/gamedata/game.droid"

    if [ $? -eq 0 ]; then
        echo "Compression completed successfully."
        mv "$TMPDIR/"* "$GAMEDIR/gamedata"
        echo "Moved compressed files to $GAMEDIR/gamedata."
        rmdir "$TMPDIR"
        echo "Temporary directory $TMPDIR removed."
        echo "Audio compression applied successfully."
    else
        echo "Audio compression failed."
        echo "Cleaning up temporary directory $TMPDIR."
        rm -rf "$TMPDIR"
    fi
}

process_game() {
    # Delete unnecessary files
    rm -rf gamedata/*.exe gamedata/*.dll gamedata/.gitkeep
    echo "Removed unecessary files"
    mv "$GAMEDIR/gamedata/data.win" "$GAMEDIR/gamedata/game.droid"

    compress_audio
    sleep 3

    # Check for .dat files and move to APK
    if [ -n "$(ls ./*.dat 2>/dev/null)" ]; then
        mkdir -p ./assets
        mv ./gamedata/gamedata/*.dat ./assets
        echo "Moved .dat files to ./assets/"

        zip -r -0 ./game.apk ./assets/
        echo "Zipped contents to ./game.apk"

        rm -rf ./assets
        echo "Deleted assets directory"
    else
        echo "No .dat files found"
    fi
	
    # Final completion message
    echo "Patching process complete!"
}

# Call the function
process_game
